blank_issues_enabled: false
contact_links:
-name: Email contacting
url: mailto:michalkichal1@outlook.com
about: If you have problem and issue reporting is not working, use this link.
-name: Luckypather page
about: If luckypather is not working and you have to enable them, enter this page
url:http://luckypatchers.com
